@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.grimmyboi.javaengineering.block.thermalgenerator;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;