@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.grimmyboi.javaengineering.block.monitor;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;